name: vercel deploy
on:
  push:
    branches:
      - master
  pull_request_target:

jobs:
  vercel-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: build
        run: yarn && yarn build
      - name: set up pr preview
        uses: ./
        id: vercel-action-staging
        if: github.event_name == 'pull_request_target'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./cloudtower-api-doc/build
          alias-domains: |
            pr-{{PR_NUMBER}}.cloudtoer-api-doc.vercle.app
      # - uses: ./
      #   id: vercel-action-production
      #   if: github.event_name == 'push'
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
      #     vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
      #     vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
      #     working-directory: ./cloudtower-api-doc/build
      #     vercel-args: '--prod'
